import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Waheed App",
  description: "Generated by create next app",
  verification: {
    google: "j9IbcoEA4BBllj25-WG3rsraFA2t1S09Ra2SF6qL7rM",
  },
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className="font-sans md:font-serif">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
